name: carpool
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  # cloud_firestore: ^4.9.1
  cloud_firestore: ^4.17.0
  custom_map_markers: ^0.0.2+1
  feather_icons: ^1.2.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  geocoding: ^2.1.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.5
  location: ^5.0.3
  ms_undraw: ^3.1.0+3
  provider: ^6.0.5
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
