name: carpool
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  feather_icons: ^1.2.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.5
  ms_undraw: ^3.1.0+3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
