name: carpool
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  feather_icons: ^1.2.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.5
  ms_undraw: ^3.1.0+3
  provider: ^6.0.5
  http: ^0.13.3
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.7
  custom_map_markers: ^0.0.1
  location: ^5.0.0
  url_launcher: ^6.1.14
  carousel_slider: ^4.2.1

assets: 
    - assets/gmaps.png
    - assets/akshay.jpeg
    - assets/emma.jpeg
    - assets/johnny.jpeg 
    - assets/srk.webp
    - assets/taylor.webp

fonts: 
    - family: Raleway 
      fonts: 
        - asset: fonts/Raleway-Black.ttf
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-Regular.ttf
    - family: InclusiveSans 
      fonts: 
        - asset: fonts/InclusiveSans-Regular.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
